<?php

namespace Dhi\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MilstarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilstarRepository extends EntityRepository {

    public function getMilstarHistoryGrid($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper, $admin = '') {

        $data = $this->trim_serach_data_milstar_history($searchData, $SearchType);

        $query = $this->createQueryBuilder('m')
                ->select('m', 'u', 'po', 'sp')
                ->leftJoin('m.user', 'u')
                ->leftJoin('m.purchaseOrder', 'po')
                ->leftJoin('po.servicePurchases', 'sp')
                ->Where('m.responseCode = :mresp')
                ->setParameter('mresp', 'A');

        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {

            $query->andWhere($likeStr);
        }

        $query->orderBy($order_by, $sort_order);

        $countData = count($query->getQuery()->getArrayResult());

        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
        $result = $query->getQuery()->getArrayResult();

        $dataResult = array();
        if (count($result) > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;

            return $dataResult;
        }

        return false;
    }

    public function trim_serach_data_milstar_history($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {

                    if ($key == 'AuthTicket' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'm.authTicket';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'RequestId' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'm.requestId';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }

                    $i++;
                }
            }
        }
        return $QueryStr;
    }

    public function getMilstarFailureHistoryGrid($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper, $admin = '') {


        $data = $this->trim_serach_data_milstar_failure_history($searchData, $SearchType);
//        echo "<pre>";
//         var_dump($data);
//         die("test to die");

        $query =$this->createQueryBuilder('m')
                ->select('m', 'u', 'po', 'sp')
                ->leftJoin('m.user', 'u')
                ->leftJoin('m.purchaseOrder', 'po')
                ->leftJoin('po.servicePurchases', 'sp')
                ->Where('m.responseCode !=  :mresp')
                ->setParameter('mresp', 'A');

        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {

            $query->andWhere($likeStr);
        }
        $query->orderBy($order_by, $sort_order);

//               echo $query->getQuery()->getSQL();
//                exit;
        $countData = count($query->getQuery()->getArrayResult());

        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
        $result = $query->getQuery()->getArrayResult();

        $dataResult = array();
        if (count($result) > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;

            return $dataResult;
        }

        return false;
    }

    public function trim_serach_data_milstar_failure_history($searchData, $SearchType) {

        $QueryStr = array();
        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {

                    if ($key == 'RequestId' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'm.requestId';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'Email' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'u.email';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }

                    if ($key == 'UserName' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'u.username';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }



                    $i++;
                }
            }
        }
        return $QueryStr;
    }

}
