<?php

namespace Dhi\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends EntityRepository
{
     public function getAllPaymentMethod() {

        $qb = $this->createQueryBuilder('pm')
                ->orderBy('pm.name', 'ASC');

        $result = $qb->getQuery()->getArrayResult();

        return $result ;

     }

     public function getSalesReportMethods() {
        $qb = $this->createQueryBuilder('pm')->where("pm.showInSalesReport = :showInSalesReport")->setParameter("showInSalesReport", true);
        $result = $qb->getQuery()->getArrayResult();
        return $result ;
     }

     public function getPaymentMethodByCode($codes) {
        $qb = $this->createQueryBuilder('pm')
        	->where('pm.code IN (:codes)')->setParameter('codes', $codes);
        $result = $qb->getQuery()->getResult();
		return $result;
     }
}
