<?php

namespace Dhi\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaypalCheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalCheckoutRepository extends EntityRepository
{
    public function getPaypalPurchaseInfo($transcationID, $user)
    {
        if($transcationID && $user){
            
            $qb = $this->createQueryBuilder('p')
                        ->select('p')
                        ->where('p.paypalTransactionId = :paypalTransactionId')
                        ->setParameter('paypalTransactionId', $transcationID)
                        ->andWhere('p.user = :user')
                        ->setParameter('user', $user);
            
            $result = $qb->getQuery()->getOneOrNullResult();
            
            return $result;
        }
        return false;
    }

    public function getPaypalDoExpressTrans()
    {
        $qb = $this->createQueryBuilder('p')
        ->select('p')
        ->where('p.paypal_process_status = :paypalProcessStatus')
        ->setParameter('paypalProcessStatus', 'DoExpressCheckOut')
        ->andWhere('p.create_timestamp < :createTimestamp')
        ->setParameter('createTimestamp', new \DateTime('-2 HOUR'));
        
        $result = $qb->getQuery()->getResult();
    
        return $result;
    }
}
