<?php

namespace Dhi\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaypalRecurringLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalRecurringLogRepository extends EntityRepository
{
	
	public function getRecurringDataForCheckNextPaymentSuccess() {
	
		$todayDatetime = new \DateTime();
		$dayAfterDatetime = $todayDatetime->modify('+1 DAY');
		
		$qb = $this->createQueryBuilder('prl')
					->select('prl')
					->where('prl.isPurchaseNotificationSend =:isPurchaseNotificationSend')
					->setParameter('isPurchaseNotificationSend', 0)
					->andWhere('prl.nextBillingDate >=:stNextBillingDate')
					->setParameter('stNextBillingDate', $dayAfterDatetime->format('Y-m-d 00:00:00'))
					->andWhere('prl.nextBillingDate <=:edNextBillingDate')
					->setParameter('edNextBillingDate', $dayAfterDatetime->format('Y-m-d 23:59:59'));
			
		$result = $qb->getQuery()->getResult();
	
		if($result) {
	
			return $result;
		}
	
		return false;
	}
}
