<?php

namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiFailureEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiFailureEmailRepository extends EntityRepository
{
	
	//Added for Gridlist
	public function getApiFailureEmailGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {
	
		$data = $this->trim_serach_data($searchData, $SearchType);
	
		$query = $this->createQueryBuilder('ae');
			
		if ($SearchType == 'ORLIKE') {
	
			$likeStr = $objHelper->orLikeSearch($data);
		}
		if ($SearchType == 'ANDLIKE') {
	
			$likeStr = $objHelper->andLikeSearch($data);
		}
	
		if ($likeStr) {
	
			$query->andWhere($likeStr);
		}
	
		$query->orderBy($orderBy, $sortOrder);
			
		$countData = count($query->getQuery()->getArrayResult());
			
		$query->setMaxResults($limit);
		$query->setFirstResult($offset);
			
		$result = $query->getQuery()->getResult();
	
		$dataResult = array();
			
		if ($countData > 0) {
	
			$dataResult['result'] = $result;
			$dataResult['totalRecord'] = $countData;
	
			return $dataResult;
		}
		return false;
	}
	
	public function trim_serach_data($searchData, $SearchType) {
	
		$QueryStr = array();
	
		if (!empty($searchData)) {
	
			if ($SearchType == 'ANDLIKE') {
	
				$i = 0;
				foreach ($searchData as $key => $val) {
	
					if ($key == 'Email' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'ae.email';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					$i++;
				}
			}
		}
		return $QueryStr;
	}
}
