<?php

namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends EntityRepository
{
    public function getChannelList($packageId, $maxShowChannels, $operation){
        
        $query = $this->createQueryBuilder('ch')
                ->select('ch.id', 'ch.name')
                ->leftJoin('ch.package', 'p')
                ->where('p.packageId = :package')
                ->setParameter('package', $packageId)
                ->andWhere('ch.status = :status')
                ->setParameter('status', true);
        
        if($operation == 'Hide'){
            $query->setMaxResults($maxShowChannels);
        }
        $result = $query->getQuery()->getArrayResult();
        $allChannel = array();
        if (!empty($result)) {
            $allChannel = array_map(function($result){ return $result['name']; }, $result);
            return $allChannel;
        }
        return $allChannel;
    }
}
