<?php

namespace Dhi\AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ChaseMerchantIdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaseMerchantIdsRepository extends EntityRepository
{
    public function getChaseMarchantIdsGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper)
    {
        $data = $this->trim_serach_data($searchData, $SearchType);
        $query = $this->createQueryBuilder('c')
                ->select('c.id, c.merchantId, c.merchantName, c.isDefault, c.createdAt, c.updatedAt, u.username, c.isActive')
                ->leftJoin('c.createdBy', 'u')
                ;
                
        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        } else if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);
        $countData = count($query->getQuery()->getArrayResult());
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
        $result = $query->getQuery()->getArrayResult();
        
        $dataResult = array();
        if ($countData > 0) {
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
            return $dataResult;
        }
        return false;
    }
    
    public function trim_serach_data($searchData, $SearchType) {
        
        $QueryStr = array();
        if (!empty($searchData)) {
            if ($SearchType == 'ANDLIKE') {
                $i = 0;
                foreach ($searchData as $key => $val) {
                    if ($key == 'MerchantId' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'c.merchantId';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'IsActive' && !empty($val)) {
                        $arrVal = array('Enable' => 1, 'Disable' => 0);
                        $QueryStr[$i]['Field'] = 'c.isActive';
                        $QueryStr[$i]['Value'] = $arrVal[$val];
                        $QueryStr[$i]['Operator'] = '=';
                    }
                    $i++;
                }
            }
        }
        return $QueryStr;
    }
    
    public function checkUniqueMerchantId($merchantId, $merchantName, $id = ''){
        
        $query = $this->createQueryBuilder('c')
                ->select('count(c.id)')
                ->where('c.merchantId = :merchantId')
                ->setParameter('merchantId', $merchantId)
                ->orWhere('c.merchantName = :merchantName')
                ->setParameter('merchantName', $merchantName)
                ;
        
        if(isset($id)){
            $query->andWhere('c.id != :id')
                  ->setParameter('id', $id);
        }
            
        $result = $query->getQuery()->getSingleScalarResult();
        return $result;
       
    }
    
    public function getActiveChaseMerchantIds()
    {
        $query = $this->createQueryBuilder('c')
                ->select('c.id, c.merchantId, c.merchantName')
                ->where('c.isActive = :isActive')
                ->setParameter('isActive', true)
                ->orderBy('c.merchantName', 'ASC')
                ;
        $result = $query->getQuery()->getArrayResult();
        return $result;
    }
            
}
