<?php

namespace Dhi\AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ChaseMerchantIdAuditLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaseMerchantIdAuditLogRepository extends EntityRepository
{
}
