<?php

namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IspPinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IspPinRepository extends EntityRepository
{
	
	//Added for Gridlist
	public function getIspPinGridList($limit = 0, $offset = 10, $orderBy = "i.id", $sortOrder = "asc", $searchData, $SearchType, $objHelper, $adminServiceLocationPermission = '') {
	
		$data = $this->trim_serach_data($searchData, $SearchType);
	
		$query = $this->createQueryBuilder('i')
		->leftJoin('i.serviceLocation', 'sl')
		->leftJoin('i.package', 'p');
			
                if($adminServiceLocationPermission != '')
                { 
                    $query->andWhere('sl.id IN (:serviceLocation)');
                    $query->setParameter('serviceLocation', $adminServiceLocationPermission);
                }   
                
		if ($SearchType == 'ORLIKE') {
	
			$likeStr = $objHelper->orLikeSearch($data);
		}
		if ($SearchType == 'ANDLIKE') {
	
			$likeStr = $objHelper->andLikeSearch($data);
		}
	
		if ($likeStr) {
	
			$query->andWhere($likeStr);
		}
	
		$query->orderBy($orderBy, $sortOrder);
			
		$countData = count($query->getQuery()->getArrayResult());
			
		$query->setMaxResults($limit);
		$query->setFirstResult($offset);
			
		$result = $query->getQuery()->getResult();
	
		$dataResult = array();
			
		if ($countData > 0) {
	
			$dataResult['result'] = $result;
			$dataResult['totalRecord'] = $countData;
	
			return $dataResult;
		}
		return false;
	}
	
	public function trim_serach_data($searchData, $SearchType) {
	
		$QueryStr = array();
	
		if (!empty($searchData)) {
	
			if ($SearchType == 'ANDLIKE') {
	
				$i = 0;
				foreach ($searchData as $key => $val) {
	
					if ($key == 'serviceLocation' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'sl.name';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					if ($key == 'package' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'p.packageName';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					if ($key == 'username' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'i.username';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					if ($key == 'password' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'i.password';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
						
					if ($key == 'validity' && !empty($val)) {
							
						$QueryStr[$i]['Field'] = 'i.validity';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
					if ($key == 'ispType' && !empty($val)) {
							
						$QueryStr[$i]['Field'] = 'i.ispType';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					$i++;
				}
			} else {
	
			}
		}
		return $QueryStr;
	}
}
