<?php

namespace Dhi\AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PaypalCredentialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalCredentialsRepository extends EntityRepository
{
    public function getCredentialGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper, $country = '')
    {
        $data = $this->trim_serach_data($searchData, $SearchType);
        $query = $this->createQueryBuilder('c')
                ->innerJoin('c.country', 'cu');

        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        } else if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        if($country != '')
        { 
            $query->andWhere('c.serviceLocations IN (:country)');
            $query->setParameter('country', $country);
        }
        
        $query->orderBy($orderBy, $sortOrder);
        $countData = count($query->getQuery()->getArrayResult());
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
        $result = $query->getQuery()->getResult();
        $dataResult = array();
        if ($countData > 0) {
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
            return $dataResult;
        }
        return false;
    }
    
    public function trim_serach_data($searchData, $SearchType) {
        $QueryStr = array();
        if (!empty($searchData)) {
            if ($SearchType == 'ANDLIKE') {
                $i = 0;
                foreach ($searchData as $key => $val) {
                     if ($key == 'Credential Id' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'c.PaypalId';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }                                   
                    $i++;
                }
            }
        }
        return $QueryStr;
    }
}
