<?php

namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SelevisionLoginHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelevisionLoginHistoryRepository extends EntityRepository
{
	public function findLoginHistory($aWhere){
		$qb = $this->createQueryBuilder('slh')->select("slh.id")
			->where("slh.user = :user")
			->setParameter('user', $aWhere['user']);

		if (!empty($aWhere['start_date'])) {
			$startDate = new \DateTime($aWhere['start_date']);
			$qb->andWhere("slh.startDate = :startDate")->setParameter('startDate', $startDate);
		}

		$result = $qb->getQuery()->getArrayResult();
		return $result;
	}

	public function getHistoryGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {
		$data = $this->trim_serach_data($searchData, $SearchType);
        $query = $this->createQueryBuilder('slh')
                ->innerJoin('slh.user', 'u');
        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }
        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);
        $countData = count($query->getQuery()->getArrayResult());
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        $result = $query->getQuery()->getResult();
        $dataResult = array();
        if ($countData > 0) {
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
            return $dataResult;
        }
        return false;
	}

	public function trim_serach_data($searchData, $SearchType) {
        $QueryStr = array();
        if (!empty($searchData)) {
            if ($SearchType == 'ANDLIKE') {
                $i = 0;
                foreach ($searchData as $key => $val) {
                    if ($key == 'username' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'u.username';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    $i++;
                }
            } else {
                
            }
        }
        return $QueryStr;
    }
}
