<?php

namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    public function getEmailCampaignDays() {
    
        $qb = $this->createQueryBuilder('s')
        ->select('s')
        ->where('s.name = :emial_campaign_days')
        ->setParameter('emial_campaign_days', 'email_campaign_days');
    
        $record = $qb->getQuery()->getOneOrNullResult();
    
        if ($record) {
            return $record->getValue();
        }
    
        return false;
    }
}
