<?php
namespace Dhi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromoCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyMonkeyMailLogRepository extends EntityRepository {
    
    public function getSurveyMonkeyLog($surveyId){
        $query = $this->createQueryBuilder('sml');
                 
        $query->where('sml.surveyId = :surveyId')
                    ->setParameter('surveyId', $surveyId);
        
        $result = $query->getQuery()->getArrayResult();
        
        return $result;
    }
}

