fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
dhi_admin:
    resource: "@DhiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


dhi_user:
    resource: "@DhiUserBundle/Resources/config/routing.yml"
    prefix:   /

dhi_topup:
    resource: "@DhiTopupBundle/Resources/config/routing.yml"
    prefix:   /


gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"