<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountrywiseServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountrywiseServiceRepository extends EntityRepository {

     public function getAllCountrywiseServiceQuery() {

        $query = $this->createQueryBuilder('c')
                      ->innerJoin('c.country', 'cy')
                      ->innerJoin('c.service', 'sr')
                      ->groupBy('c.country');

        return $query;
    }
    
    public function getAllCountrywiseServiceSearch($query, $search) {
        
        $query->where('cy.name LIKE :cname')
        ->setParameter('cname', '%'.$search.'%');
       
        return $query;
    }
    
    public function getAllActiveCountrywiseService($county = NULL) {
        $query = $this->createQueryBuilder('c')
                      ->select('sr.name, sr.id')
                      ->innerJoin('c.services', 'sr')
                      ->where('c.status = :csts')
                      ->setParameter('csts', 1)
                      ->andWhere('sr.status = :ssts')
                      ->setParameter('ssts', 1);
                      
                  if($county) {
                      $query->andWhere('c.country = :country')
                      ->setParameter('country', $county);        
                  }
        
        return $query->getQuery()->getArrayResult();
    }
}
