<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeactivateWithOutMacUserServiceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeactivateWithOutMacUserServiceLogRepository extends EntityRepository
{
}
