<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailCampaignRepository extends EntityRepository
{
     
    //Added for Gridlist
    public function getEmailCampaignGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {
        
        $data = $this->trim_serach_data($searchData, $SearchType);
        
        $query = $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'desc');
               
                 

        if ($SearchType == 'ORLIKE') {

            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {

            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {

            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);
       
        $countData = count($query->getQuery()->getArrayResult());
           
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
       
        $result = $query->getQuery()->getResult();
        
        $dataResult = array();
       
        if ($countData > 0) {
            
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
           
            return $dataResult;
        }
        return false;
    }
    
     public function trim_serach_data($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {

                    if ($key == 'Subject' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'e.subject';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }

                    if ($key == 'SentAt' && !empty($val)) {
                        $date = explode('~', $val);
                        $fromDate = trim($date[0]);
                        $toDate = trim($date[1]);

                        if ($fromDate != "") {
                            $startDate = new \DateTime($fromDate);
                            $QueryStr[$i]['Field'] = 'e.sentAt';
                            $QueryStr[$i]['Value'] = $startDate->format('Y-m-d 00:00:00');
                            $QueryStr[$i]['Operator'] = '>=';
                         }
                         if ($toDate != "") {
                            $i++;
                            $endDate = new \DateTime($toDate);
                            $QueryStr[$i]['Field'] = 'e.sentAt';
                            $QueryStr[$i]['Value'] = $endDate->format('Y-m-d 23:59:59');
                            $QueryStr[$i]['Operator'] = '<=';
                         }
                    }

                    if ($key == 'EmailType' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'e.emailType';
                        $QueryStr[$i]['Value'] = $val == 'Marketing' ? 'M' : 'S';
                        $QueryStr[$i]['Operator'] = '=';
                    }
                    
                     if ($key == 'Status' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'e.emailStatus';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = '=';
                    }                                   
                    $i++;
                }
            } else {
                
            }
        }
        return $QueryStr;
    }
}
