<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FrontHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontHomeRepository extends EntityRepository
{

	 public function getFrontHomeGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {

        $data = $this->trim_serach_data($searchData, $SearchType);

        $query = $this->createQueryBuilder('fh')
                ->select('fh')
                ->leftJoin('fh.country', 'c')
                ->orderBy('fh.id', 'desc');
               

        if ($SearchType == 'ORLIKE') {

            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {

            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {

            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);

        $countData = count($query->getQuery()->getArrayResult());

        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        $result = $query->getQuery()->getResult();

        $dataResult = array();

        if ($countData > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;

            return $dataResult;
        }
        return false;
    }

     public function trim_serach_data($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {

                     if ($key == 'Country' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'c.name';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
//
//                    if ($key == 'EmailType' && !empty($val)) {
//
//                        $QueryStr[$i]['Field'] = 'e.emailType';
//                        $QueryStr[$i]['Value'] = $val == 'Marketing' ? 'M' : 'S';
//                        $QueryStr[$i]['Operator'] = '=';
//                    }
//
//                     if ($key == 'Status' && !empty($val)) {
//
//                        $QueryStr[$i]['Field'] = 'e.emailStatus';
//                        $QueryStr[$i]['Value'] = $val;
//                        $QueryStr[$i]['Operator'] = '=';
//                    }
                    $i++;
                }
            } else {

            }
        }
        return $QueryStr;
    }
}
