<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolarWindsSupportLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolarWindsSupportLocationRepository extends EntityRepository {
    
    public function getSolarWindsLocationGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {
        
        $data = $this->trim_serach_data($searchData, $SearchType);
        $query = $this->createQueryBuilder('sw')
                ->select('sw.id, sl.name AS supportLocationName, so.requestTypeName, st.companyName,st.domain,sw.createdAt, sw.updatedAt, cu.username')
                ->leftJoin('sw.supportLocation', 'sl')
                ->leftJoin('sw.solarWindsRequestType', 'so')
                ->leftJoin('sw.supportsite', 'st')
                ->leftJoin('sw.createdBy', 'cu')
                ->where('sw.isDeleted = :isdeleted')
                ->setParameter('isdeleted', 0);


        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        } else if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);

        $countQuery   = clone $query;
        $countQuery->select("count(sw.id) as totalRecords");
        $objCountData = $countQuery->getQuery()->getOneOrNullResult();
        $countData    = $objCountData['totalRecords'];

        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
        $result = $query->getQuery()->getArrayResult();

        $dataResult = array();
        if ($countData > 0) {
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
            return $dataResult;
        }
        return false;
    }

    public function trim_serach_data($searchData, $SearchType) {
        
        $QueryStr = array();
        if (!empty($searchData)) {
            if ($SearchType == 'ANDLIKE') {
                $i = 0;
                foreach ($searchData as $key => $val) {
                    if ($key == 'supportLocation' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'sl.name';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = '=';
                    }
                    if ($key == 'solarWindsRequestType' && !empty($val)) {
                        $QueryStr[$i]['Field'] = 'so.requestTypeName';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = '=';
                    }
                    if ($key == 'supportsite' && !empty($val)) {
                        
                        $sitarray = explode('-', $val);
                        $sitename = trim($sitarray[0]);
                        
                        $QueryStr[$i]['Field'] = 'st.companyName';
                        $QueryStr[$i]['Value'] = $sitename;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    
                    $i++;
                }
            }
        }
        return $QueryStr;
    }

    
    public function getaassignedlocation($siteid){
        $query = $this->createQueryBuilder('sw')
                ->select('sl.id')
                ->leftJoin('sw.supportLocation', 'sl')
                ->leftJoin('sw.supportsite', 'st')
                ->where('sw.isDeleted = :isdeleted')
                ->setParameter('isdeleted', 0)
                ->andwhere('st.id = :siteid')
                ->setParameter('siteid', $siteid);
                
        $result = $query->getQuery()->getArrayResult();
        
        return $result;
    }
}
