<?php

namespace Dhi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SupportLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportLocationRepository extends EntityRepository {
    
    //Added for Gridlist
    public function getSupportLocationGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper) {
        
        $data = $this->trim_serach_data($searchData, $SearchType);
        
        $query = $this->createQueryBuilder('c')
                      ->select('c')
                      ->leftjoin('c.supportsite','wl')
                      ->leftjoin('c.createdBy','cu')
                      ->where('c.isDeleted = :isdeleted')
                      ->setParameter('isdeleted', 0);
             
                 
        if ($SearchType == 'ORLIKE') {

            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {

            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {

            $query->andWhere($likeStr);
        }

        $query->orderBy($orderBy, $sortOrder);
       
        $countData = count($query->getQuery()->getArrayResult());
           
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);
       
        $result = $query->getQuery()->getResult();
        
        $dataResult = array();
       
        if ($countData > 0) {
            
            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;
           
            return $dataResult;
        }
        return false;
    }
      // added For Searching
     public function trim_serach_data($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {
                    
                     if ($key == 'Location' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'c.name';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = '=';
                    }

                    if ($key == 'supportsite' && !empty($val)) {

                        $QueryStr[$i]['Field'] = 'wl.id';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = '=';
                        
                    }
                    
                    $i++;
                }
            } else {
                
            }
        }
        return $QueryStr;
    } 

 
    public function getSiteWiseSupportLocaion($arrParams = array()){
        
        if(!empty($arrParams)){
            
            if($arrParams['oldSequenceNum'] < $arrParams['newSequenceNum']){
                $newSeqOperator = '<=';
                $oldSeqOperator = '>';
            }else{
                $newSeqOperator = '>=';
                $oldSeqOperator = '<';
            }
            $query = $this->createQueryBuilder('sl')
                    ->where('sl.supportsite = :siteId')
                    ->setParameter('siteId', $arrParams['supportsiteId'])
                    ->andWhere('sl.sequenceNumber '.$newSeqOperator.' :newSequenceNum')
                    ->setParameter('newSequenceNum', $arrParams['newSequenceNum'])
                    ->andWhere('sl.sequenceNumber '.$oldSeqOperator.' :oldSequenceNum')
                    ->setParameter('oldSequenceNum', $arrParams['oldSequenceNum'])
                    ->andWhere('sl.isDeleted = :isdeleted')
                    ->setParameter('isdeleted', 0)
                    ->orderBy('sl.sequenceNumber', 'asc');
            $result = $query->getQuery()->getResult();
            
            if(count($result)){
                return $result;
            }
            return false;
        }
    }

    
     public function getAllSupportLocation() {

        $qb = $this->createQueryBuilder('sl')
                  ->where('sl.isDeleted = :isdeleted')
                  ->setParameter('isdeleted', 0)
                  ->orderBy('sl.name', 'asc')->groupBy('sl.name');

        $result = $qb->getQuery()->getArrayResult();

	return $result ;

     }
     
     public function getSitewiseLocation($siteId,$existlocation){
         $qb = $this->createQueryBuilder('sl')
                 ->select('sl.id','sl.name')
                 ->leftjoin('sl.supportsite','st')
                 ->where('st.id = :siteId')
                 ->setparameter('siteId',$siteId)
                 ->andWhere('sl.isDeleted = :isdeleted')
                 ->setParameter('isdeleted', 0);
                 
                 if($existlocation){
                     $qb->andwhere($qb->expr()->notIn('sl.id', $existlocation));
                 }
                $qb ->orderBy('sl.name', 'asc');
        $result = $qb->getQuery()->getArrayResult();
	return $result ;
     }
     
     public function getSupportLocationForUpdateSequenceNum($arrParams = array()){
         if($arrParams){
            $query = $this->createQueryBuilder('sl')
                    ->where('sl.supportsite = :supportsite')
                    ->setParameter('supportsite', $arrParams['siteId'])
                    ->andWhere('sl.sequenceNumber > :seqenceNum')
                    ->setParameter('seqenceNum', $arrParams['sequenceNumber'])
                    ->andWhere('sl.isDeleted = :isdeleted')
                    ->setParameter('isdeleted', 0);
                    
            $result = $query->getQuery()->getResult();
            if(count($result) > 0){
                return $result;
            }
         }
         return false;
         
     }
    
    public function checkSupportLocationName($siteId, $name, $id = 0){
        $query = $this->createQueryBuilder('sl')
                ->select('sl')
                ->where('sl.name = :locationName')
                ->setParameter("locationName", $name)
                ->andWhere('sl.supportsite = :supportsite')
                ->setParameter("supportsite", $siteId)
                ->andWhere('sl.isDeleted = :is_deleted')
                ->setParameter("is_deleted", 0);
        if(!empty($id)){
                $query->andWhere('sl.id <> :id')->setParameter("id", $id);
        }
        $result = $query->getQuery()->getResult();
        return $result;
    }
}
